/**                                      -*- mode:C++ -*- */

/***********************         DO NOT EDIT        ******************************
*
* C2D.h - Quark header for ULAM //gcnl:SymbolClass.cpp:760
*
**********************************************************************************
* This code is generated by the ULAM programming language compilation system.
*
* The ULAM programming language compilation system is free software:
* you can redistribute it and/or modify it under the terms of the GNU
* General Public License as published by the Free Software
* Foundation, either version 3 of the License, or (at your option)
* any later version.
*
* The ULAM programming language compilation system is distributed in
* the hope that it will be useful, but WITHOUT ANY WARRANTY; without
* even the implied warranty of MERCHANTABILITY or FITNESS FOR A
* PARTICULAR PURPOSE.  See the GNU General Public License for more
* details.
*
* You should have received a copy of the GNU General Public License
* along with the ULAM programming language compilation system
* software.  If not, see <http://www.gnu.org/licenses/>.
*
* @license GPL-3.0+ <http://spdx.org/licenses/GPL-3.0+>
*/

#ifndef UQ_102323C2D10_H
#define UQ_102323C2D10_H

#include "UlamDefs.h"
#include "Uq_102323C2D10_Types.h"
//Forward Defs of other classes: //gcnl:SymbolTableOfClasses.cpp:595
namespace MFM { template <class EC> struct Uq_10106UrSelf10; }  //FORWARD
namespace MFM { template <class EC> struct Ue_10105Empty10; }  //FORWARD

namespace MFM{

  template <class EC> //gcnl:NodeBlockClass.cpp:1338
  struct Uq_102323C2D10 : public UlamQuark<EC> /*, Uq_10106UrSelf10 */
  {

    // Extract short names for parameter types
    typedef typename EC::ATOM_CONFIG AC;
    typedef typename AC::ATOM_TYPE T;
    enum { BPA = AC::BITS_PER_ATOM };

    typedef BitVector<BPA> BV; //gcnl:NodeBlockClass.cpp:1621
    typedef BitField<BitVector<BPA>, VD::BITS, T::ATOM_FIRST_STATE_BIT, 0> BFTYP; //gcnl:NodeBlockClass.cpp:1624

    enum { 
      QUARK_SIZE = 32 /* Requiring quarks to advertise their size in a std way.) */
    }; //gcnl:NodeBlockClass.cpp:1367

    typedef UlamRefFixed<EC, 0u, QUARK_SIZE> Up_Us; //entire quark //gcnl:NodeBlockClass.cpp:1371

    Uq_102323C2D10(); //gcnl:NodeBlockClass.cpp:1377
    ~Uq_102323C2D10(); //gcnl:NodeBlockClass.cpp:1382

    static Uq_102323C2D10 THE_INSTANCE; //gcnl:NodeBlockClass.cpp:1388

//! C2D.ulam:11:   typedef Int(16) Coord;

//! C2D.inc:3:   typedef Unsigned(3) Dir;

//! C2D.inc:5:   Coord x = 0;
    typedef UlamRefFixed<EC, 0u, 16u> Up_Um_1x; //gcnl:NodeVarDeclDM.cpp:1107

//! C2D.inc:6:   Coord y = 0;
    typedef UlamRefFixed<EC, 16u, 16u> Up_Um_1y; //gcnl:NodeVarDeclDM.cpp:1107

    void Uf_4Self(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Uq_102323C2D10<EC>& Uv_1s) const; //gcnl:SymbolFunction.cpp:485

    void Uf_4Self(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Ut_102161i<EC>& Uv_2ax, Ui_Ut_102161i<EC>& Uv_2ay) const; //gcnl:SymbolFunction.cpp:485

    void Uf_3set(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Uq_102323C2D10<EC>& Uv_1c) const; //gcnl:SymbolFunction.cpp:485

    void Uf_3set(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Ut_102321i<EC>& Uv_2ax, Ui_Ut_102321i<EC>& Uv_2ay) const; //gcnl:SymbolFunction.cpp:485

    Ui_Uq_r102323C2D10<EC> Uf_9211_operator3d(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Uq_102323C2D10<EC>& Uv_5other) const; //gcnl:SymbolFunction.cpp:485

    Ui_Uq_r102323C2D10<EC> Uf_9213_operator2b3d(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Uq_102323C2D10<EC>& Uv_5other) const; //gcnl:SymbolFunction.cpp:485

    Ui_Uq_r102323C2D10<EC> Uf_9213_operator2d3d(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Uq_102323C2D10<EC>& Uv_5other) const; //gcnl:SymbolFunction.cpp:485

    Ui_Uq_102323C2D10<EC> Uf_5clamp(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Uq_102323C2D10<EC>& Uv_5below, Ui_Uq_102323C2D10<EC>& Uv_5above) const; //gcnl:SymbolFunction.cpp:485

    Ui_Ut_102321i<EC> Uf_4getX(const UlamContext<EC>& uc, UlamRef<EC>& ur) const; //gcnl:SymbolFunction.cpp:485

    Ui_Ut_102321i<EC> Uf_4getY(const UlamContext<EC>& uc, UlamRef<EC>& ur) const; //gcnl:SymbolFunction.cpp:485

    void Uf_4setX(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Ut_102321i<EC>& Uv_2ax) const; //gcnl:SymbolFunction.cpp:485

    void Uf_4setY(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Ut_102321i<EC>& Uv_2ay) const; //gcnl:SymbolFunction.cpp:485

    Ui_Uq_102323C2D10<EC> Uf_4make(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Ut_102321i<EC>& Uv_1x, Ui_Ut_102321i<EC>& Uv_1y) const; //gcnl:SymbolFunction.cpp:485

    Ui_Ut_10111b<EC> Uf_6equals(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Uq_102323C2D10<EC>& Uv_5other) const; //gcnl:SymbolFunction.cpp:485

    Ui_Ut_10111b<EC> Uf_9213_operator3d3d(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Uq_102323C2D10<EC>& Uv_5other) const; //gcnl:SymbolFunction.cpp:485

    Ui_Ut_10111b<EC> Uf_9213_operator213d(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Uq_102323C2D10<EC>& Uv_5other) const; //gcnl:SymbolFunction.cpp:485

    Ui_Uq_102323C2D10<EC> Uf_3max(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Uq_102323C2D10<EC>& Uv_5other) const; //gcnl:SymbolFunction.cpp:485

    Ui_Uq_102323C2D10<EC> Uf_9211_operator7c(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Uq_102323C2D10<EC>& Uv_5other) const; //gcnl:SymbolFunction.cpp:485

    Ui_Uq_r102323C2D10<EC> Uf_9213_operator7c3d(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Uq_102323C2D10<EC>& Uv_5other) const; //gcnl:SymbolFunction.cpp:485

    Ui_Uq_102323C2D10<EC> Uf_3min(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Uq_102323C2D10<EC>& Uv_5other) const; //gcnl:SymbolFunction.cpp:485

    Ui_Uq_102323C2D10<EC> Uf_9211_operator26(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Uq_102323C2D10<EC>& Uv_5other) const; //gcnl:SymbolFunction.cpp:485

    Ui_Uq_r102323C2D10<EC> Uf_9213_operator263d(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Uq_102323C2D10<EC>& Uv_5other) const; //gcnl:SymbolFunction.cpp:485

    Ui_Ut_10111b<EC> Uf_8contains(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Uq_102323C2D10<EC>& Uv_5other) const; //gcnl:SymbolFunction.cpp:485

    Ui_Ut_102321i<EC> Uf_3dot(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Uq_102323C2D10<EC>& Uv_5other) const; //gcnl:SymbolFunction.cpp:485

    Ui_Ut_102321i<EC> Uf_9211_operator2a(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Uq_102323C2D10<EC>& Uv_5other) const; //gcnl:SymbolFunction.cpp:485

    Ui_Uq_102323C2D10<EC> Uf_3add(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Uq_102323C2D10<EC>& Uv_5other) const; //gcnl:SymbolFunction.cpp:485

    Ui_Uq_102323C2D10<EC> Uf_9211_operator2b(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Uq_102323C2D10<EC>& Uv_5other) const; //gcnl:SymbolFunction.cpp:485

    Ui_Uq_102323C2D10<EC> Uf_9211_operator2b(const UlamContext<EC>& uc, UlamRef<EC>& ur) const; //gcnl:SymbolFunction.cpp:485

    Ui_Uq_102323C2D10<EC> Uf_8subtract(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Uq_102323C2D10<EC>& Uv_5other) const; //gcnl:SymbolFunction.cpp:485

    Ui_Uq_102323C2D10<EC> Uf_9211_operator2d(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Uq_102323C2D10<EC>& Uv_5other) const; //gcnl:SymbolFunction.cpp:485

    Ui_Uq_102323C2D10<EC> Uf_9211_operator2d(const UlamContext<EC>& uc, UlamRef<EC>& ur) const; //gcnl:SymbolFunction.cpp:485

    Ui_Uq_102323C2D10<EC> Uf_6negate(const UlamContext<EC>& uc, UlamRef<EC>& ur) const; //gcnl:SymbolFunction.cpp:485

    Ui_Uq_102323C2D10<EC> Uf_8neighbor(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Ut_10131u<EC>& Uv_1d) const; //gcnl:SymbolFunction.cpp:485

    Ui_Uq_102323C2D10<EC> Uf_6corner(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Ut_10131u<EC>& Uv_1d) const; //gcnl:SymbolFunction.cpp:485

    Ui_Ut_102321u<EC> Uf_6length(const UlamContext<EC>& uc, UlamRef<EC>& ur) const; //gcnl:SymbolFunction.cpp:485

    Ui_Ut_102321u<EC> Uf_9217manhattanDistance(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Uq_102323C2D10<EC>& Uv_5other) const; //gcnl:SymbolFunction.cpp:485

    Ui_Ut_10111b<EC> Uf_8isOrigin(const UlamContext<EC>& uc, UlamRef<EC>& ur) const; //gcnl:SymbolFunction.cpp:485

    Ui_Uq_102323C2D10<EC> Uf_3abs(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Uq_102323C2D10<EC>& Uv_2of) const; //gcnl:SymbolFunction.cpp:485

    Ui_Uq_102323C2D10<EC> Uf_3abs(const UlamContext<EC>& uc, UlamRef<EC>& ur) const; //gcnl:SymbolFunction.cpp:485

    Ui_Ut_102321u<EC> Uf_9224euclideanSquaredDistance(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Uq_102323C2D10<EC>& Uv_5other) const; //gcnl:SymbolFunction.cpp:485

    Ui_Ut_102321u<EC> Uf_9222euclideanSquaredLength(const UlamContext<EC>& uc, UlamRef<EC>& ur) const; //gcnl:SymbolFunction.cpp:485

    //BUILT-IN FUNCTIONS:

    const UlamClassDataMemberInfo & GetDataMemberInfo(u32 dataMemberNumber) const; //gcnl:NodeBlockClass.cpp:2663

    s32 GetDataMemberCount() const; //gcnl:NodeBlockClass.cpp:2727

    const char * GetMangledClassName() const; //gcnl:NodeBlockClass.cpp:2778

    virtual u32 GetClassLength() const; //gcnl:NodeBlockClass.cpp:1992

    virtual const unsigned char * GetString(u32 sidx) const; //gcnl:NodeBlockClass.cpp:2508

    virtual u32 GetStringLength(u32 sidx) const; //gcnl:NodeBlockClass.cpp:2578

    virtual u32 getDefaultQuark( ) const; //gcnl:NodeBlockClass.cpp:2134

    enum VTABLE_IDX {
      VTABLE_IDX_Uf_6behave10 = 0,
      VTABLE_IDX_Uf_8getColor11102321u,
      VTABLE_IDX_MAX
    }; //gcnl:NodeBlockClass.cpp:2278

    static VfuncPtr m_vtable[2]; //gcnl:NodeBlockClass.cpp:2285
    virtual VfuncPtr getVTableEntry(u32 idx) const; //gcnl:NodeBlockClass.cpp:2289

    //helper method not called directly
    bool internalCMethodImplementingIs(const UlamClass<EC> * cptrarg) const; //gcnl:NodeBlockClass.cpp:1933

    __inline__ const u32 GetPos() const { return 0u; }
  };

  template<class EC>
  Uq_102323C2D10<EC> Uq_102323C2D10<EC>::THE_INSTANCE;



} //MFM

#include "Uq_102323C2D10.tcc"
#endif //UQ_102323C2D10_H
