/**                                      -*- mode:C++ -*- */

/***********************         DO NOT EDIT        ******************************
*
* DebugUtils.h - Quark header for ULAM //gcnl:SymbolClass.cpp:760
*
**********************************************************************************
* This code is generated by the ULAM programming language compilation system.
*
* The ULAM programming language compilation system is free software:
* you can redistribute it and/or modify it under the terms of the GNU
* General Public License as published by the Free Software
* Foundation, either version 3 of the License, or (at your option)
* any later version.
*
* The ULAM programming language compilation system is distributed in
* the hope that it will be useful, but WITHOUT ANY WARRANTY; without
* even the implied warranty of MERCHANTABILITY or FITNESS FOR A
* PARTICULAR PURPOSE.  See the GNU General Public License for more
* details.
*
* You should have received a copy of the GNU General Public License
* along with the ULAM programming language compilation system
* software.  If not, see <http://www.gnu.org/licenses/>.
*
* @license GPL-3.0+ <http://spdx.org/licenses/GPL-3.0+>
*/

#ifndef UQ_10109210DEBUGUTILS10_H
#define UQ_10109210DEBUGUTILS10_H

#include "UlamDefs.h"
#include "Uq_10109210DebugUtils10_Types.h"
//Forward Defs of other classes: //gcnl:SymbolTableOfClasses.cpp:595
namespace MFM { template <class EC> struct Uq_10106UrSelf10; }  //FORWARD
namespace MFM { template <class EC> struct Uq_102323C2D10; }  //FORWARD
namespace MFM { template <class EC> struct Ue_10105Empty10; }  //FORWARD

namespace MFM{

  template <class EC> //gcnl:NodeBlockClass.cpp:1338
  struct Uq_10109210DebugUtils10 : public UlamQuark<EC> /*, Uq_10106UrSelf10 */
  {

    // Extract short names for parameter types
    typedef typename EC::ATOM_CONFIG AC;
    typedef typename AC::ATOM_TYPE T;
    enum { BPA = AC::BITS_PER_ATOM };

    typedef BitVector<BPA> BV; //gcnl:NodeBlockClass.cpp:1621
    typedef BitField<BitVector<BPA>, VD::BITS, T::ATOM_FIRST_STATE_BIT, 0> BFTYP; //gcnl:NodeBlockClass.cpp:1624

    enum { 
      QUARK_SIZE = 0 /* Requiring quarks to advertise their size in a std way.) */
    }; //gcnl:NodeBlockClass.cpp:1367

    typedef UlamRefFixed<EC, 0u, QUARK_SIZE> Up_Us; //entire quark //gcnl:NodeBlockClass.cpp:1371

    Uq_10109210DebugUtils10(); //gcnl:NodeBlockClass.cpp:1377
    ~Uq_10109210DebugUtils10(); //gcnl:NodeBlockClass.cpp:1382

    static Uq_10109210DebugUtils10 THE_INSTANCE; //gcnl:NodeBlockClass.cpp:1388

//! DebugUtils.ulam:9:   constant Bits cPRINT_SYMBOL =          0x00000001; //< Include element symbol

//! DebugUtils.ulam:10:   constant Bits cPRINT_FULL_NAME =       0x00000002; //< Include element name

//! DebugUtils.ulam:11:   constant Bits cPRINT_ATOM_BODY =       0x00000004; //< Include entire atom in hex

//! DebugUtils.ulam:12:   constant Bits cPRINT_MEMBER_VALUES =   0x00000008; //< Include data member values

//! DebugUtils.ulam:13:   constant Bits cPRINT_MEMBER_BITVALS =  0x00000010; //< Include data member values as bits in hex

//! DebugUtils.ulam:14:   constant Bits cPRINT_MEMBER_NAMES =    0x00000020; //< Include data member names

//! DebugUtils.ulam:15:   constant Bits cPRINT_MEMBER_TYPES =    0x00000040; //< Include data member types

//! DebugUtils.ulam:16:   constant Bits cPRINT_SIZE0_MEMBERS =   0x00000080; //< Include size 0 data members

//! DebugUtils.ulam:17:   constant Bits cPRINT_MEMBER_ARRAYS =   0x00000100; //< Print array values individually

//! DebugUtils.ulam:18:   constant Bits cPRINT_RECURSE_QUARKS =  0x00000200; //< Print quarks recursively

//! DebugUtils.ulam:19:   constant Bits cPRINT_INDENTED_LINES =  0x00000400; //< Add newlines and indents

//! DebugUtils.ulam:21:   constant Bits cPRINT_NOTHING = Unsigned.minof;

//! DebugUtils.ulam:22:   constant Bits cPRINT_HEX_ATOM = cPRINT_SYMBOL|cPRINT_ATOM_BODY;

//! DebugUtils.ulam:23:   constant Bits cPRINT_TOP_MEMBERS = cPRINT_SYMBOL|cPRINT_MEMBER_VALUES;

//! DebugUtils.ulam:24:   constant Bits cPRINT_MEMBERS = cPRINT_SYMBOL|cPRINT_MEMBER_NAMES|cPRINT_MEMBER_VALUES;

//! DebugUtils.ulam:25:   constant Bits cPRINT_QUARK_MEMBERS = cPRINT_MEMBERS|cPRINT_RECURSE_QUARKS;

//! DebugUtils.ulam:26:   constant Bits cPRINT_ALL_MEMBERS = cPRINT_SYMBOL|cPRINT_MEMBER_VALUES|cPRINT_RECURSE_QUARKS|cPRINT_MEMBER_ARRAYS;

//! DebugUtils.ulam:27:   constant Bits cPRINT_EVERYTHING = Unsigned.maxof;

    void Uf_5print(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Ut_102961a<EC>& Uv_3arg) const; //gcnl:SymbolFunction.cpp:485

    void Uf_5print(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Ut_102961a<EC>& Uv_1a, Ui_Ut_102321t<EC>& Uv_5flags) const; //native //gcnl:SymbolFunction.cpp:481

    void Uf_5print(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Ut_102321s<EC>& Uv_3arg) const; //native //gcnl:SymbolFunction.cpp:481

    void Uf_5print(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Uq_102323C2D10<EC>& Uv_3arg) const; //native //gcnl:SymbolFunction.cpp:481

    void Uf_5print(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Ut_10141i<EC>& Uv_3arg) const; //native //gcnl:SymbolFunction.cpp:481

    void Uf_5print(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Ut_10131i<EC>& Uv_3arg) const; //native //gcnl:SymbolFunction.cpp:481

    void Uf_5print(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Ut_10131y<EC>& Uv_3arg) const; //native //gcnl:SymbolFunction.cpp:481

    void Uf_5print(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Ut_10131b<EC>& Uv_3arg) const; //native //gcnl:SymbolFunction.cpp:481

    void Uf_5print(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Ut_102321i<EC>& Uv_3arg) const; //native //gcnl:SymbolFunction.cpp:481

    void Uf_5print(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Ut_102321u<EC>& Uv_3arg) const; //native //gcnl:SymbolFunction.cpp:481

    Ui_Ut_10111b<EC> Uf_9214hasEventWindow(const UlamContext<EC>& uc, UlamRef<EC>& ur) const; //native //gcnl:SymbolFunction.cpp:481

    void Uf_9212printContext(const UlamContext<EC>& uc, UlamRef<EC>& ur) const; //gcnl:SymbolFunction.cpp:485

    void Uf_9212printContext(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Ut_102321t<EC>& Uv_5flags) const; //native //gcnl:SymbolFunction.cpp:481

    void Uf_919printChar(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Ut_10181u<EC>& Uv_3arg) const; //native //gcnl:SymbolFunction.cpp:481

    void Uf_6assert(const UlamContext<EC>& uc, UlamRef<EC>& ur, Ui_Ut_10111b<EC>& Uv_1b) const; //native //gcnl:SymbolFunction.cpp:481

    //BUILT-IN FUNCTIONS:

    const UlamClassDataMemberInfo & GetDataMemberInfo(u32 dataMemberNumber) const; //gcnl:NodeBlockClass.cpp:2663

    s32 GetDataMemberCount() const; //gcnl:NodeBlockClass.cpp:2727

    const char * GetMangledClassName() const; //gcnl:NodeBlockClass.cpp:2778

    virtual u32 GetClassLength() const; //gcnl:NodeBlockClass.cpp:1992

    virtual const unsigned char * GetString(u32 sidx) const; //gcnl:NodeBlockClass.cpp:2508

    virtual u32 GetStringLength(u32 sidx) const; //gcnl:NodeBlockClass.cpp:2578

    virtual u32 getDefaultQuark( ) const; //gcnl:NodeBlockClass.cpp:2134

    enum VTABLE_IDX {
      VTABLE_IDX_Uf_6behave10 = 0,
      VTABLE_IDX_Uf_8getColor11102321u,
      VTABLE_IDX_MAX
    }; //gcnl:NodeBlockClass.cpp:2278

    static VfuncPtr m_vtable[2]; //gcnl:NodeBlockClass.cpp:2285
    virtual VfuncPtr getVTableEntry(u32 idx) const; //gcnl:NodeBlockClass.cpp:2289

    //helper method not called directly
    bool internalCMethodImplementingIs(const UlamClass<EC> * cptrarg) const; //gcnl:NodeBlockClass.cpp:1933

    __inline__ const u32 GetPos() const { return 0u; }
  };

  template<class EC>
  Uq_10109210DebugUtils10<EC> Uq_10109210DebugUtils10<EC>::THE_INSTANCE;



} //MFM

#include "Uq_10109210DebugUtils10.tcc"
#include "Uq_10109210DebugUtils10_native.tcc"
#endif //UQ_10109210DEBUGUTILS10_H
